name: armTemplateDeployment
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:

  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIAL}}

      - name: Deploy Resource Group rg-github-action with az cli
        uses: Azure/cli@v1
        with: 
          inlineScript: |
            az deployment sub create --location "west europe" --template-file ./arm-templates/resourcegroup.json

           
